# Generated by Django 4.1.7 on 2023-03-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiintegration', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='seed',
            field=models.IntegerField(default=782973255683),
        ),
    ]
