# Generated by Django 4.1.7 on 2023-04-03 09:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aiintegration', '0003_alter_prompt_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='height',
            field=models.SmallIntegerField(default=512, validators=[django.core.validators.MinValueValidator(128), django.core.validators.MaxValueValidator(1024)]),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='is_final',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='is_template',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='seed',
            field=models.IntegerField(blank=True, default=14051),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='width',
            field=models.SmallIntegerField(default=512, validators=[django.core.validators.MinValueValidator(128), django.core.validators.MaxValueValidator(1024)]),
        ),
    ]
