# Generated by Django 4.1.7 on 2023-04-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiintegration', '0004_alter_image_image_alter_prompt_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_path',
        ),
        migrations.AlterField(
            model_name='prompt',
            name='seed',
            field=models.IntegerField(blank=True, default=7784329),
        ),
    ]
