# Generated by Django 4.1.7 on 2023-04-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiintegration', '0011_alter_prompt_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='seed',
            field=models.IntegerField(blank=True, default=7982130),
        ),
    ]
