# Generated by Django 4.1.7 on 2023-04-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiintegration', '0014_prompt_created_at_prompt_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='seed',
            field=models.IntegerField(blank=True, default=5582822),
        ),
    ]
