# Generated by Django 4.1.7 on 2023-04-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust_and_stuff', '0002_alter_customer_last_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='delivery_address',
            field=models.ManyToManyField(blank=True, to='cust_and_stuff.deliveryaddress', verbose_name='customers'),
        ),
    ]
