# Generated by Django 4.1.7 on 2023-04-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust_and_stuff', '0003_alter_customer_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
