# Generated by Django 4.1.7 on 2023-04-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_manufacturer_remove_item_price_itemwithcolor_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
