# Generated by Django 4.1.7 on 2023-04-05 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_manufacturer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('chest_size', models.IntegerField(help_text='Chest size in cm')),
                ('waist_size', models.IntegerField(help_text='Waist size in cm')),
                ('hip_size', models.IntegerField(help_text='Hip size in cm')),
                ('dress_length', models.IntegerField(help_text='Dress length in cm')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
        migrations.AddField(
            model_name='itemwithcolor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='itemwithcolor',
            name='item_code',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='itemwithcolor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='itemwithcolor',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.size'),
        ),
    ]
