# Generated by Django 4.1.7 on 2023-04-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_size_remove_item_size_itemwithcolor_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemwithcolor',
            name='size',
        ),
        migrations.AddField(
            model_name='itemwithcolor',
            name='size',
            field=models.ManyToManyField(to='shop.size'),
        ),
    ]
