# Generated by Django 4.1.7 on 2023-04-14 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aiintegration', '0015_alter_prompt_seed'),
        ('shop', '0007_alter_order_shipped_alter_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='prompt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aiintegration.prompt', verbose_name='prompt'),
        ),
    ]
